# Generated by Django 4.2.10 on 2024-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='ticker',
            field=models.CharField(choices=[('TSLA', 'TSLA'), ('UBER', 'UBER'), ('AAPL', 'AAPL'), ('AMZN', 'AMZN'), ('AMD', 'AMD'), ('RIOT', 'RIOT'), ('NVDA', 'NVDA'), ('NFLX', 'NFLX'), ('SNAP', 'SNAP'), ('META', 'META')], max_length=5),
        ),
    ]
