# Generated by Django 4.2.10 on 2024-02-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date_closed',
            field=models.DateField(blank=True),
        ),
    ]
