# Generated by Django 4.2.10 on 2024-02-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_trade_broker_alter_trade_closing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.CharField(choices=[('ETORO', 'ETORO'), ('ROBINHOOD', 'ROBINHOOD'), ('IG', 'IG'), ('DEGIRO', 'DEGIRO'), ('INTERACTIVE BROKERS', 'INTERACTIVE BROKERS'), ('PLUS500', 'PLUS500')], default='Null', max_length=20),
            preserve_default=False,
        ),
    ]
