# Generated by Django 4.2.10 on 2024-02-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_trade_closing_price_alter_trade_opening_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['date_opened']},
        ),
    ]
